### ISSUE TITLE
chef-client timer disable error

### ISSUE THREAD

**Issue by knaveenr** [chef-cookbooks/chef-client#514] opened 2017-08-10 13:28 UTC
### Cookbook version
v8.1.8

### Chef-client version
chef-12.14.89-1.el7.x86_64

### Platform Details
CentOS Linux release 7.3.1611 (Core)

### Scenario:
On first chef run, chef-client recipe fails at  
systemd_unit[chef-client.timer] (chef-client::systemd_service line 67) 

### Steps to Reproduce:
CentOS 7.3, chef-12.14.89-1, Chef-client v8.1.8

### Expected Result:
Chef-client successful run

### Actual Result:
Exits with stack trace

Stack Trace:
Generated at 2017-08-10 06:17:43 -0500
Mixlib::ShellOut::ShellCommandFailed: systemd_unit[chef-client.timer] (chef-client::systemd_service line 67) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /usr/bin/systemctl --system disable chef-client.timer ----
STDOUT:
STDERR: Operation failed: No such file or directory
---- End output of /usr/bin/systemctl --system disable chef-client.timer ----
Ran /usr/bin/systemctl --system disable chef-client.timer returned 1
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-shellout-2.2.7/lib/mixlib/shellout.rb:289:in `invalid!'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-shellout-2.2.7/lib/mixlib/shellout.rb:276:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/mixin/shell_out.rb:55:in `shell_out_with_systems_locale!'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/provider/systemd_unit.rb:204:in `systemctl_execute!'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/provider/systemd_unit.rb:93:in `block in action_disable'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/provider.rb:176:in `converge_by'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/provider/systemd_unit.rb:92:in `action_disable'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/provider.rb:145:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/resource.rb:603:in `run_action'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/client.rb:669:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/client.rb:664:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/client.rb:664:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/client.rb:703:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/client.rb:283:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/application.rb:302:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/application.rb:290:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/application.rb:290:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/application.rb:255:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/application.rb:243:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.89/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:54:in `load'
/usr/bin/chef-client:54:in `<main>'

>>>> Caused by Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /usr/bin/systemctl --system disable chef-client.timer ----
STDOUT:
STDERR: Operation failed: No such file or directory
---- End output of /usr/bin/systemctl --system disable chef-client.timer ----
Ran /usr/bin/systemctl --system disable chef-client.timer returned 1

**Comment by kamaradclimber** [comment] 2018-03-15 08:53
Impacted by this as well. I can't figure out yet why chef would fail with action `:disable` when the unit does not exist.

**Comment by kamaradclimber** [comment] 2018-03-16 09:35
In our case, this happens only in a chrooted environment (in our postinstall sequence) and is due to https://bugzilla.redhat.com/show_bug.cgi?id=1110675

`systemctl is-enabled chef-client.timer` outputs an error but exit with 0 (instead of 3 as on a normal system)
but
`systemctl disable chef-client.timer` fails with an exit code >0.

**Comment by kamaradclimber** [comment] 2018-03-16 09:38
A workaround is to update systemd package to 219-42.el7_4.4 (we were using 219-30.el7_3.6)

**Comment by dheerajd-msys** [comment] 2019-10-03 12:01
Hi there,

I've tried to reproduce this issue with `kitchen` and applied the same cookbook version i.e. 8.1.8 and also for the  `chef v12.14.89` on `centos 7`, but kitchen finishes off perfectly fine.

**Below is the output of Kitchen Execution** : 
```
       Recipe: chef-client::systemd_service
         * directory[/var/run/chef] action create
           - create new directory /var/run/chef
           - change owner from '' to 'root'
           - change group from '' to 'root'
           - restore selinux security context
         * directory[/var/cache/chef] action create
           - create new directory /var/cache/chef
           - change owner from '' to 'root'
           - change group from '' to 'root'
           - restore selinux security context
         * directory[/var/lib/chef] action create
           - create new directory /var/lib/chef
           - change owner from '' to 'root'
           - change group from '' to 'root'
           - restore selinux security context
         * directory[/var/log/chef] action create
           - create new directory /var/log/chef
           - change mode from '' to '0755'
           - change owner from '' to 'root'
           - change group from '' to 'root'
           - restore selinux security context
         * directory[/etc/chef] action create
           - create new directory /etc/chef
           - change owner from '' to 'root'
           - change group from '' to 'root'
           - restore selinux security context
         * template[/etc/sysconfig/chef-client] action create
           - create new file /etc/sysconfig/chef-client
           - update content in file /etc/sysconfig/chef-client from none to ec7de1
           --- /etc/sysconfig/chef-client       2019-10-03 04:54:11.947186449 -0700
           +++ /etc/sysconfig/.chef-chef-client20191003-5355-1c9f89g    2019-10-03 04:54:11.946186450 -0700
           @@ -1 +1,15 @@
           +# Configuration file for the chef-client service
           +
           +CONFIG=/etc/chef/client.rb
           +PIDFILE=/var/run/chef/client.pid
           +#LOCKFILE=/var/lock/subsys/chef-client
           +# Sleep interval between runs.
           +# This value is in seconds.
           +INTERVAL=1800
           +# Maximum amount of random delay before starting a run. Prevents every client
           +# from contacting the server at the exact same time.
           +# This value is in seconds.
           +SPLAY=300
           +# Any additional chef-client options.
           +OPTIONS=""
           - change mode from '' to '0644'
           - restore selinux security context
         * systemd_unit[chef-client.service] action create
         Recipe: <Dynamically Defined Resource>
           * file[/etc/systemd/system/chef-client.service] action create
             - create new file /etc/systemd/system/chef-client.service
             - update content in file /etc/systemd/system/chef-client.service from none to 72baea
             --- /etc/systemd/system/chef-client.service        2019-10-03 04:54:12.058186356 -0700
             +++ /etc/systemd/system/.chef-chef-client20191003-5355-b9xh2z.service      2019-10-03 04:54:12.057186357 -0700
             @@ -1 +1,15 @@
             +[Unit]
             +Description = Chef Client daemon
             +After = network.target auditd.service
             +
             +[Service]
             +Type = simple
             +EnvironmentFile = /etc/sysconfig/chef-client
             +ExecStart = /usr/bin/chef-client -c $CONFIG -i $INTERVAL -s $SPLAY $OPTIONS
             +ExecReload = /bin/kill -HUP $MAINPID
             +SuccessExitStatus = 3
             +Restart = always
             +
             +[Install]
             +WantedBy = multi-user.target
             - change mode from '' to '0644'
             - change owner from '' to 'root'
             - change group from '' to 'root'
             - restore selinux security context
           - creating unit: chef-client.service
       Recipe: chef-client::systemd_service
         * service[chef-client] action enable
           - enable service service[chef-client]
         * service[chef-client] action start
           - start service service[chef-client]
         * systemd_unit[chef-client.timer] action stop (up to date)
         * systemd_unit[chef-client.timer] action disable (up to date)
         * systemd_unit[chef-client.timer] action delete (up to date)
         * service[chef-client] action restart
           - restart service service[chef-client]

       Running handlers:
       Running handlers complete
       Chef Client finished, 11/14 resources updated in 02 seconds
       Downloading files from <default-centos-7>
       Finished converging <default-centos-7> (0m31.84s).
-----> Kitchen is finished. (0m45.92s)
```
Please let us know if I am missing anything.

Thanks!!

**Comment by dheerajd-msys** [comment] 2019-10-07 05:40
@knaveenr @kamaradclimber Please confirm if you are still facing issues.

Thanks!

**Comment by dheerajd-msys** [comment] 2019-10-14 07:00
I am closing this issue at this moment based on above comments.

**Closed by dheerajd-msys** 2019-10-14 07:00 UTC
