### ISSUE TITLE
Default Attributes for Logging Being Ignored by Chef-Client

### ISSUE THREAD

**Issue by kylegoch** [chef-cookbooks/chef-client#454] opened 2017-01-03 21:17 UTC
### Cookbook version
7.0.3

### Chef-client version
12.17.44

### Platform Details
Ubuntu 16.04

### Scenario:
Don't send logs to `/var/log/syslog`, only send them to `node.chef_client['log_dir']`

### Steps to Reproduce:
Run list of:
```
chef-client::default
chef-client::config
```

Using all default attributes provided by the `chef-client` cookbook

### Expected Result:
Logs should get sent to `/var/log/chef/client.log` as set by the default attributes

### Actual Result:
Every chef-client interval logs to `/var/log/syslog` instead of `/var/log/chef/client.log`. In fact nothing appears at `/var/log/chef/client.log`

Here is `/etc/chef/client.rb` as generated by the cookbook:
```
chef_server_url "<removed>"
client_fork true
log_location "/var/log/chef/client.log"
validation_client_name "chef-validator"
verify_api_cert true
node_name "<removed>"

# Do not crash if a handler is missing / not installed yet
begin
rescue NameError => e
  Chef::Log.error e
end
```

Here is `/etc/default/chef-client` as generate by the cookbook:
```
CONFIG=/etc/chef/client.rb
INTERVAL=1800
SPLAY=300
```

**Comment by robertstinnett** [comment] 2017-02-06 22:16
I can confirm this is also an issue/bug when running on CentOS 7.  We had to write a custom cookbook to get the log_location property set.

**Comment by lamont-granquist** [comment] 2017-04-05 05:18
might be a dup of the issue fixed by https://github.com/chef/ohai/pull/955

**Comment by rgriffith** [comment] 2017-08-29 13:50
I am also running into this behavior, where our cron scheduled check-ins are not being sent to `var/log/chef`. In fact, the directory is completely empty.

### Cookbook version
8.1.8

### Chef-client version
12.19.36

### Platform Details
Amazon Linux AMI release 2016.09

### Steps to Reproduce

**Attributes in wrapping cookbook:**

```
default['chef_client']['init_style'] = 'none'
default['chef_client']['log_rotation']['postrotate'] = ''
default['chef_client']['cron']['hour'] = '6'
default['chef_client']['cron']['weekday'] = '2,4'
```

**Recipe code:**

```
include_recipe 'chef-client::cron'
```

**Comment by fishermanswharff** [comment] 2017-10-31 23:30
I've had luck specifying the `daemon_options` via attributes: 
```ruby
default['chef_client']['daemon_options'] = ['-l', 'debug', '-L', "#{node['chef_client']['log_dir']}/#{node['chef_client']['log_file']}"]
```

**Comment by majormoses** [comment] 2019-05-24 05:40
Hmm this is a fairly old issue so before I start investing any time I would like to make sure its still happening and that I understand the reported behavior.
- is this still an issue? The referenced ohai issue is quite old and if that was the root cause it would be fixed in any reasonably new chef-client.
- I notice there is a `node['chef_client']['cron']['log_file']` but no `node['chef_client']['cron']['log_level']` is that expected? Could that be what is causing it to not behave as expected? This was particularly interesting based on @fishermanswharff comment about requiring both being set when using the daemon
- In the `client.rb` we are not leveraging any of the log config options: https://github.com/chef-cookbooks/chef-client/blob/v11.2.0/recipes/config.rb#L85-L93 other than by using the `node['chef_client']['config']['options']` is anyone using that and it is not rendering properly? If using it and rendered properly does it work as expected? My guess is that we should be adding those options to set them directly. We could technically move them into the `node['chef_client']['config']` hash but that would I think be a needless breaking change.

I think it does make sense that both in the context of cron and a daemonized service that it should not use `client.rb` for these values and should configure them differently for manually kicking off a `chef-client` run vs the daemon or cron methods. For example in your config you might want to have your cron/daemon runs to go to a central logging server and force the logger format which is more machine readable but when I am manually kicking it off to leave the logger format and location alone so I can see `std(out|err)` in a more human friendly format.

I don't see anyone actually setting: [node['chef_client']['cron']['log_file']](https://github.com/chef-cookbooks/chef-client/blob/v11.2.0/recipes/cron.rb#L97) in any of the snippets and it [defaults](https://github.com/chef-cookbooks/chef-client/blob/v11.2.0/attributes/default.rb#L59) to `/dev/null`.

After looking a bit through the cookbook and what has been shared here I wonder if it's less of one or more bugs and more about poor UX due to the many namespaces and required knowledge of which options may need to be set together. If its the latter we could minimally put in some warnings in the logs when you set one required attribute but not another. Anyways let me know what your thoughts are.

**Comment by lamont-granquist** [comment] 2019-11-14 18:05
Given that it looks like this cookbook is correctly rendering the log_location attribute into config.rb and that the reported bugs are against ancient and unsupported 12.x clients I'm going to close it.  Looks like this cookbook has been working correctly and any bugs were likely against chef-client itself.  Definitely not an actionable ticket.

**Closed by lamont-granquist** 2019-11-14 18:05 UTC
