### ISSUE TITLE
chef-client does not start every 30 minutes

### ISSUE THREAD

**Issue by kmanohar1** [chef-cookbooks/chef-client#464] opened 2017-02-28 20:02 UTC
### Cookbook version
I bootstrapped WITHOUT using '--sudo' option and I do see that chef-client cookbook created /etc/init.d/chef-client and it ran every 30 minutes. All looked good.

I bootstrapped WITH '--sudo' option and I do see that chef-client cookbook created /etc/init.d/chef-client but it did NOT run every 30 minutes. Am I missing something?

**Comment by iennae** [comment] 2017-03-02 03:45
@kmanohar1 Can you provide logs and more information for your run? The issue template helps us to understand your situation better. Please let us know the following:

Cookbook version

[Version of the cookbook where you are encountering the issue]

Chef-client version

[Version of chef-client in your environment]

Platform Details

[Operating system distribution and release version. Cloud provider if running in the cloud]

Scenario:

[What you are trying to achieve and you can't?]

Steps to Reproduce:

[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]

Expected Result:

[What are you expecting to happen as the consequence of above reproduction steps?]

Actual Result:

[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

**Comment by kmanohar1** [comment] 2017-03-02 14:53
Can you please let me know which log file you want to see? Thanks

**Comment by xuxogarcia** [comment] 2017-03-06 20:40
When I bootstrapped my test Ubuntu 16.04 node without sudo, /etc/init.d/chef-client was not created either. I added _recipe[chef-client::systemd_service]_ to my role and the unit was created but I still see this error on the logs:

INFO: Could not determine service init style, manual intervention required to start up the chef-client service

My configuration is not updating at all due to this.

If I do a systemctl status, it gives feedback:

_chef-client.service - Chef Client daemon
   Loaded: loaded (/etc/systemd/system/chef-client.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2017-03-06 20:31:01 UTC; 9min ago
 Main PID: 30355 (chef-client)
   CGroup: /system.slice/chef-client.service
           └─30355 /opt/chef/embedded/bin/ruby --disable-gems /usr/bin/chef-client -c /etc/chef/client.rb -i 43200 -s 60_

**Comment by xuxogarcia** [comment] 2017-03-06 21:00
@iennae btw...

Cookbook version: 7.2.0
Chef client: 12.19.36
Ubuntu: 16.04 (AWS)

Scenario:
Changing default runtime to test configuration (from 30 mins to 5 mins)

Reproduce:
Bootstrap node as root, no sudo

Expected result:
/etc/init.d/chef-client created after role applied

Actual result:
No service file & no configuration changes

**Comment by iennae** [comment] 2017-03-07 01:26
Thanks for the update! Appreciate the further details on how to replicate the issue.

**Comment by jpSimkins** [comment] 2017-05-06 05:53
I too have this issue

**Comment by seththoenen** [comment] 2017-05-17 18:54
I'm having the same issue on Linux distros. Windows Server (2008 R2, 2012R2, 2016) seems to be checking in on a regular interval.

Cookbook version: 8.1.1
Chef client: 13.0.118
Distros Effected: CentOS 7, Ubuntu 14.04

Scenario:
Upgraded chef-client from 12.18.31 -> 13.0.118

Reproduce:
CentOS 7 and Ubuntu 14.04 system, running chef-client 12.18.31 with chef-client cookbook 8.1.1. Keep intervals at the default 30 minute check in time. Upgrade chef-client to 13.0.118 with the following commands:
CentOS 7: `sudo rpm -Uvh [path to chef-client 13]`
Ubuntu 14.04: `sudo dpkg -i [path to chef-client 13]`

Expected result:
Chef-client to check in at a regular interval.

Actual result:
Chef-client no longer checks in on a regular interval.

**Comment by iennae** [comment] 2017-05-18 02:31
@seththoenen thanks for adding information. I think it might be a separate issue, but you might want to check out https://supermarket.chef.io/cookbooks/chef_client_updater for updating chef_client. If you install software while it's running you can have unknown results. In general you want to stop, upgrade, start software.

**Comment by vmazyluk** [comment] 2017-08-10 11:07
I had the same problem. 
Just restarting chef-client service on all nodes did the trick.

**Comment by donwlewis** [comment] 2017-10-30 16:11
So I am having this issue, but restarting the service does not resolve the issue.  I am running chef-client version `13.5.3`  and OS `RHEL 7.4`

**Comment by sfiggins** [comment] 2017-11-05 16:24
Same problem as donlewis noted, only using chef-client version 13.4.24 and rhel 7.4.  Nodes on which I have installed chef 12 are working fine. Service reports no errors, but does not check in with the expected interval.

**Comment by sfiggins** [comment] 2017-11-05 16:32
I think this might be a chef problem rather than a cookbook problem I see in my processes that the interval is getting passed to the chef-client: 

```/opt/chef/embedded/bin/ruby --disable-gems /usr/bin/chef-client -c /etc/chef/client.rb -i 1800 -s 300```

So I think the cookbook is doing the right thing.

**Comment by seththoenen** [comment] 2017-11-06 14:07
I've switched my Linux nodes to use the chef-client cookbook's `cron` recipe and I've had pretty good success thus far. Using `cron` should also mitigate any issues upgrading chef-client, however I haven't tested this yet.

**Comment by donwlewis** [comment] 2017-11-06 16:37
@sfiggins I have a case opened with Chef regarding this because, as you say, the configuration looks right, but doesn't seem to actually run.  I can update you directly once I hear back.

@seththoenen cron is definitely an option, but I just don't know how figure out the splay would work.  Not sure if this cookbook will do that for you.

**Comment by sfiggins** [comment] 2017-11-28 19:42
Upgrading to chef 13.6.4 seems to have resolved the problem for me, reinforcing my opinion that this was a problem with the application, not the cookbook.

**Comment by donwlewis** [comment] 2017-11-28 20:35
Yup.  There was an issue with the sleep interval in chef-client.  Was
resolved ins 13.6.4.

**Comment by iennae** [comment] 2017-11-29 21:29
@sfiggins and @donwlewis Thanks so much for confirming this! @kmanohar1 it looks like this is resolved with a later chef. Please reopen if you are still having issues.

**Closed by iennae** 2017-11-29 21:29 UTC
Labels: Type: Bug

**Comment by jagan495** [comment] 2018-12-23 16:59
/etc/init.d/chef-client cookbook not created with below version, Any help is greatly appreciated. 

chef-client -v
Chef: 14.8.12

**Comment by MandyPandax3** [comment] 2019-04-15 14:22
I am having the same issue as jagan495. Unable to update the interval/splay attributes for the chef-client cookbook. 

Chef-Client Version: 14.8.12

**Comment by iennae** [comment] 2019-04-24 03:03
hey @MandyPandax3 and @jagan495 the problem that was being reported before was resolved, please open a new issue with more details about what you are experiencing as the specific problem that was happening was resolved in 13.6.4. By updating this closed issue it's not bringing attention to this new issue (that might have the same symptoms). Thanks!
