### ISSUE TITLE
init.d chef-client service is not restarted when the config file is changed during a chef-run

### ISSUE THREAD

**Issue by dreamnite** [chef-cookbooks/chef-client#377] opened 2016-03-24 20:39 UTC
If the /etc/chef/client.rb file is changed during a run, the running chef-client service is not notified to restart. 
The file is reloaded for the current run, but  modifications do not appear to be used by future runs launched by the still running service.

**Comment by hgregorian** [comment] 2016-09-29 06:00
+1 on this, with some additional context (and insight?)

Recently, we decided (due to upstream changes in the Ohai cookbook) to move our custom ohai plugins to /etc/chef/ohai/plugins/ (previously /etc/chef/ohai_plugins/ -- should be noted that this was Chef's original path for custom plugins). This involved making a change to the client.rb to use the new path. Any changes to the client.rb require, at minimum a "reload". After deploying the changes, we observed non-idempotent runs wherein there was a message, something to the effect "client.rb doesn't specify /etc/chef/ohai/plugins, so we're adding it to this run and reloading the plugins". Odd to see this given that this path was in client.rb and that the reload attribute was enabled in the upstream chef-client cookbook. It also seemed curious that by issuing a service chef-client reload or kill -1 <chef-client PID> or kill -HUP <chef-client PID> would resolve the issue. Calling `Chef::Config.from_file(path_to_client_rb)` reloads config in the context of the run, and has ZERO impact on a daemonized chef instance. Perhaps intended for chef-client runs being executed by a cron, not as a daemon?

In initial testing towards a work-around, our wrapper cookbook set `default['chef_client']['reload_config']` to `false` (the chef-client cookbook applies a conditional notifies to the do-nothing config reload https://github.com/chef-cookbooks/chef-client/blob/master/recipes/config.rb#L94) and appended the `client.rb` template resource (by modifying the resource collection) to notify a reload of the chef-client service.  This had no effect.  Turns out, that due the behavior of the service resource on the RHEL family, "supports" for reload is false.  We discovered that one can notify a service to reload all day and receive no errors (and no results) UNLESS supports reload is true.  Not wanting to redefine the chef-client service in the wrapper, a second modification to the resource collection was made on the chef-client service resource to indicate that reload was supported.  A bit kludgy, yes, totally functional and expected?...absolutely.

**Comment by dheerajd-msys** [comment] 2020-02-10 10:46
Hi @dreamnite 
Latest chef-client cookbook `v11.4.0` is reloading the `client.rb` properly and modifications gets reflected while service is running.
Followed steps to reproduce the issue : 
1. Bootstrap ubuntu 16 VM and applied run list `chef-client::config` to run the service in every 10 seconds.
2. ## Before Config file change
```
azure@dh-ubu16:~$ ps aux | grep chef
root      35287  0.0  0.7 191312 63068 ?        Ss   Feb06   0:08 /opt/chef/embedded/bin/ruby --disable-gems /usr/bin/chef-client -c /etc/chef/client.rb -i 10 -s 300
azure    112185  0.0  0.0  12944  1092 pts/0    S+   09:39   0:00 grep --color=auto chef
azure@dh-ubu16:~$ cat /etc/chef/client.rb 

chef_server_url "https://api.chef.io/organizations/msystech"
log_location "/var/log/chef/client.log"
validation_client_name "msystech-validator"
verify_api_cert false
node_name "dh-ubu16"
```
3. Updated cookbook template client.rb and uploaded the cookbook on server.
4. ## After Config file change 
Note `chef_license` update in client.rb
```
azure@dh-ubu16:~$ ps aux |grep chef
root      35287  0.0  0.7 191312 63068 ?        Ss   Feb06   0:08 /opt/chef/embedded/bin/ruby --disable-gems /usr/bin/chef-client -c /etc/chef/client.rb -i 10 -s 300
azure    118509  0.0  0.0  12944   896 pts/0    S+   10:42   0:00 grep --color=auto chef
azure@dh-ubu16:~$ cat /etc/chef/client.rb 

chef_license "accept"
chef_server_url "https://api.chef.io/organizations/msystech"
log_location "/var/log/chef/client.log"
validation_client_name "msystech-validator"
verify_api_cert false
node_name "dh-ubu16"

```
Closing as everything seems perfect.

**Closed by dheerajd-msys** 2020-02-10 10:46 UTC
Labels: Type: Bug
