### ISSUE TITLE
chef-client breaks with "403" Forbidden during bootstrap

### ISSUE THREAD

**Issue by andreidum** [chef-cookbooks/chef-client#690] opened 2020-06-23 16:43 UTC
## Description

Bootstrapping boxes running chef-client 11.5.0 (either [latest](https://github.com/chef-cookbooks/chef-client/commit/edc69c81dc474a95c88762f32bb00d445bea418a) or v11.5.0) break with the following error on the client side:
```
template[/etc/sysconfig/chef-client] action create
(remote-exec):
(remote-exec):     ================================================================================
(remote-exec):     Error executing action `create` on resource 'template[/etc/sysconfig/chef-client]'
(remote-exec):     ================================================================================

(remote-exec):     Net::HTTPServerException
(remote-exec):     ------------------------
(remote-exec):     403 "Forbidden"

```

A subsequent chef-client run seems to solve the issue. I am quite puzzled as the cookbook is cached locally.
We are using defaults for ```no_lazy_load true``` on the client side and ```['opscode-erchef']['s3_url_ttl'] = 28800``` on the server-side, so it doesn't look like a timeout waiting on the server. 

## Workarounds
This is what works:
 * Using Chef Infra v15.2.20 and chef-client v11.2.0
 * Chef Infra v16.1.16 and a patched [recipes/systemd_service.rb](https://github.com/chef-cookbooks/chef-client/compare/v11.5.0...andreidum:11.5.1-fork) chef-client cookbook.
 * chef infra v16.1.16 and hosted chef.
### chef-client
16.1.16, but was able to reproduce with 15.2.20
```
cat /etc/redhat-release
CentOS Linux release 8.1.1911 (Core)
```
### chef-server
```
[root@chef-server-1 ~]# rpm -qa |grep chef
chef-server-core-13.2.0-1.el7.x86_64
chef-manage-2.5.16-1.el7.x86_64
chef-16.1.16-1.el7.x86_64
```
# Client Output
```
 (remote-exec):     ------------------------
 (remote-exec):     403 "Forbidden"

 (remote-exec):     Resource Declaration:
 (remote-exec):     ---------------------
 (remote-exec):     # In /var/chef/cache/cookbooks/chef-client/recipes/systemd_service.rb

 (remote-exec):      28: env_file = template "/etc/#{conf_dir}/#{env_file}" do
 (remote-exec):      29:   source "default/#{dist_dir}/#{conf_dir}/chef-client.erb"
 (remote-exec):      30:   mode '0644'
 (remote-exec):      31:   notifies :restart, 'service[chef-client]', :delayed
 (remote-exec):      32: end
 (remote-exec):      33:

 (remote-exec):     Compiled Resource:
 (remote-exec):     ------------------
 (remote-exec):     # Declared in /var/chef/cache/cookbooks/chef-client/recipes/systemd_service.rb:28:in `from_file'

 (remote-exec):     template("/etc/sysconfig/chef-client") do
 (remote-exec):       action [:create]
 (remote-exec):       default_guard_interpreter :default
 (remote-exec):       source "default/redhat/sysconfig/chef-client.erb"
 (remote-exec):       declared_type :template
 (remote-exec):       cookbook_name "chef-client"
 (remote-exec):       recipe_name "systemd_service"
 (remote-exec):       owner nil
 (remote-exec):       group nil
 (remote-exec):       mode "0644"
 (remote-exec):       variables {}
 (remote-exec):       path "/etc/sysconfig/chef-client"
 (remote-exec):       verifications []
 (remote-exec):     end

 (remote-exec):     System Info:
 (remote-exec):     ------------
 (remote-exec):     chef_version=16.1.16
 (remote-exec):     platform=centos
 (remote-exec):     platform_version=8.1.1911
 (remote-exec):     ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
 (remote-exec):     program_name=/usr/bin/chef-client
```

```
knife node show mynode.mydomain -a chef_client
  chef_client:
    backup_path:    /var/lib/chef
    bin:            /usr/bin/chef-client
    cache_path:     /var/cache/chef
    chef_license:   accept
    chkconfig:
      start_order: 98
      stop_order:  2
    conf_dir:       /etc/chef
    config:
      chef_server_url:         https://chef-server-1.mydomain/organizations/myorg/
      exception_handlers:
      log_level:               info
      log_location:            STDOUT
      node_name:               mynode.mydomain
      report_handlers:
      start_handlers:
      syntax_check_cache_path: /var/chef/syntaxcache
      validation_client_name:  myorg/-validator
      verbose_logging:         true
      verify_api_cert:         true
    cron:
      append_log:            false
      environment_variables:
      hour:                  0,4,8,12,16,20
      log_file:              /dev/null
      mailto:
      minute:                0
      nice_path:             /bin/nice
      path:
      use_cron_d:            false
      weekday:               *
    daemon_options:
      -f
      -L /var/log/chef/client.log
    init_style:     systemd
    interval:       1800
    load_gems:
    log_dir:        /var/log/chef
    log_file:       client.log
    log_perm:       640
    log_rotation:
      options:
        compress
        missingok
        notifempty
      postrotate:
      prerotate:
    logrotate:
      frequency: daily
      rotate:    30
    reload_config:  true
    run_path:       /var/run/chef
    server_url:     https://chef-server-1.domain/organizations/myorg
    splay:          300
    systemd:
      restart: always
      timeout: false
      timer:   true
    task:
      frequency:          minute
      frequency_modifier: 30
      name:               chef-client
      password:
      start_date:
      start_time:
      user:               SYSTEM
```
# erchef.log
```
020-06-17 22:49:52.743 [error] {<<"method=GET; path=/organizations/myorg/; status=403; ">>,"Forbidden"}
```
# Stacktrace
```
Generated at 2020-06-17 20:13:02 +0000
Net::HTTPServerException: template[/etc/sysconfig/chef-client] (chef-client::systemd_service line 28) had an error: Net::HTTPServerException: 403 "Forbidden"
/opt/chef/embedded/lib/ruby/2.7.0/net/http/response.rb:124:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/http.rb:239:in `streaming_request'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/cookbook/remote_file_vendor.rb:66:in `get_filename'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/cookbook_version.rb:307:in `preferred_filename_on_disk_location'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/provider/template_finder.rb:40:in `find'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/provider/template/content.rb:32:in `template_location'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/provider/template.rb:43:in `block in define_resource_requirements'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/mixin/why_run.rb:309:in `assert'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/provider/template.rb:41:in `define_resource_requirements'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/provider.rb:207:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/resource.rb:591:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/runner.rb:74:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/runner.rb:108:in `each'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/runner.rb:108:in `run_all_actions'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/runner.rb:132:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/resource_collection/stepable_iterator.rb:115:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/resource_collection/stepable_iterator.rb:86:in `step'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/runner.rb:130:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/client.rb:714:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/client.rb:709:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/client.rb:709:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/client.rb:733:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/client.rb:288:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/application.rb:292:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/application.rb:268:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/application.rb:251:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/application/base.rb:335:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/application.rb:68:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.1.16/bin/chef-client:25:in `<top (required)>'
/usr/bin/chef-client:171:in `load'
/usr/bin/chef-client:171:in `<main>'
```

**Comment by lamont-granquist** [comment] 2020-08-05 00:25
This might be a bug in this cookbook, but offhand it just looks like it explodes with the first template resource that it hits, which happens to be this resource.  But there's nothing here which indicates a root cause.  The real problem is why the template file is either not getting synchronized or is not where it is supposed to be. If the run list was changing the location of the cookbook cache path that would cause it to not be there, but would also cause all the recipes to not be found, so I'd expect other hard errors to happen.  Or something could be manually removing those cookbook files from the cache I guess.  But offhand with the information at hand here it seems impossible for this to happen with `no_lazy_load true` set.  So I can't suggest what else might be wrong, or have any idea of what the bug really is.  If you can boil it down to a test-kitchen recipe which can be pushed up to github, then it could be replicated and investigated, but if this is something that only happens in your environment, then its going to be hard/impossible to debug remotely.

**Comment by lamont-granquist** [comment] 2020-08-05 07:41
probably fixed by https://github.com/chef-cookbooks/chef-client/pull/697

**Closed by lamont-granquist** 2020-08-05 07:41 UTC
