### ISSUE TITLE
chef-client daemon doesn't receive needed environment variables

### ISSUE THREAD

**Issue by giorgian** [chef-cookbooks/chef-client#473] opened 2017-04-12 13:41 UTC
### Cookbook version
3.5.0, 8.0.0

### Chef-client version
12.19.36

### Platform Details
Centos 6, Centos 7

### Scenario:
Chef client, launched by daemon (rather than launched by a human as user root) doesn't get most environment variables, notably USER and HOME.

This means, for instance, that a `/root/.gemrc` file will be read when chef-client is run from the command line, and will not be read (`/.gemrc` will be checked instead) otherwise.

### Steps to Reproduce:
Just have `chef-client` in run list and wait for the convergence to run.

### Expected Result:
Ruby internals know that the user running chef client is `root`, whose home is `/root`.

### Actual Result:
Ruby internals don't know who the user running chef is nor where their home is.

**Comment by cheeseplus** [comment] 2017-04-12 15:35
Is this an issue with the cookbook or the behavior chef-client itself?

**Comment by giorgian** [comment] 2017-04-13 07:12
That's a good question; I assume it's the cookbook, as it creates the init script, which seems a good place for the environment variables to be set.

**Comment by chakatz** [comment] 2017-04-18 14:37
I'm having a similar environment variable problem.
I was running running version '7.2.0' of this cookbook with 'chef-client::cron' in my run_list and Chef Client, version '12.18.31' on Centos 7, Ubuntu 14.04 & Ubuntu 16.04 and all was happy.

I just upgraded to Chef Client, version '13.0.118' and started having environment variable problems. In my case a convergence run cannot find 'visudo' when trying to run the sudo cookbook and I get the error:
`Errno::ENOENT: No such file or directory - visudo`

When I run the chef-client command from shell prompt or even with 'at' it works fine.
I tried upgrading to 'chef-client' cookbook version '8.0.1' but it did not help.

Looks like something changed in the newer versions of chef-client which broke this cookbook. Not sure if the fix has to be in this cookbook or in the client?

**Comment by lamont-granquist** [comment] 2017-05-02 19:33
@chakatz that is related to removing the mangling of the PATH that chef-client used to do automatically, and isn't a bug in this cookbook and that report isn't relevant to this issue which was reported first on 12.19.36

That is almost certainly due to /usr/sbin and /sbin not being in the default PATH on centos 6/7 and 13.x no longer adding those automatically.  It works on the command line because you have a .bashrc or something else which adds those to your user account.  That is a bug in the sudo cookbook (its possible that chef-client's execute resource might need some syntactic sugar to help work around this problem, but that was a deliberate breaking change in 13 and the sudo cookbook needs to be updated either way).

**Comment by lamont-granquist** [comment] 2017-05-02 19:47
As far as the original report goes, AFAIK we're not overwriting USER or HOME anywhere and we're trying to be more careful going forwards in Chef-13 about not obliterating or mangling the environment variables that we're sent.

If the problem was with older Ubuntu and upstart I'd be eager to blame the init system for not passing in the correct environment variables.   I'd still suggest validating that the cronjob or whatever was seeing the correct $HOME variable, because if you can't replace the chef-client command with `echo $HOME > /tmp/home.out` and get the correct value then chef-client wouldn't be getting the correct value.

Its also possible that some cookbook you're using is mangling ENV in some way and trashing `ENV['HOME']` and its not got anything to do with chef-client or the cookbook.  You can throw the one-liner `puts ENV['HOME']` into a libraries/whatever.rb file anywhere in a cookbook in your runlist and you should get the value of $HOME printed very early (right after synchronization and before any recipe code runs) -- if that looks correct, then the issue is later in the run_list, if that is wrong, but the cronjob/whatever is passing in the right $HOME then that would be better evidence that chef-client itself is mangling it (still would be puzzling, but that would pretty much narrow it down to core client code).  Same goes for $USER as well.

**Comment by dal13002** [comment] 2018-05-18 03:04
The workaround I found is to make the basic PATH variable before cron kicks off the "chef-client" run for linux.
```
node.default['chef_client']['cron']['environment_variables'] = "export PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin;"
```
I think this is not really chef's fault. If you give exact paths for all your commends they will work. But for whatever reason we did not need to do this for chef-client version 12.x; only after upgrading to chef-client 14.x does chef not automatically define this PATH.

**Comment by lamont-granquist** [comment] 2019-11-14 18:15
Might accept PRs to add HOME and PATH by default to templates for services as convenience if everyone needs to do that (PRs accepted).

But this is correct behavior. It changed in 13.0 as a breaking change to have chef-client no longer inject all kinds of PATH variables, etc.  That means that if your O/S does not have /sbin, /usr/sbin, etc in the PATH correctly or does not set HOME for root-run cronjobs, that chef-client faithfully does not mangle that, and its part of managing those distros that you need to add those values.

Closing this as it is really correct.  If someone would like to argue to setup those env vars by default, that's best done by submitting PRs to just do it.

**Closed by lamont-granquist** 2019-11-14 18:15 UTC
Labels: Triage: Needs Information
